/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/lighter/result.gltf --transform 
Files: public/assets/lighter/result.gltf [2.81MB] > /Users/liamellis/Desktop/fls/result-transformed.glb [358.68KB] (87%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
	const { nodes, materials } = useGLTF("/result-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.geometry_0.geometry}
				material={materials.material}
			/>
		</group>
	);
}

useGLTF.preload("/result-transformed.glb");
