import type { Metadata } from "next";
import { Poppins, Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
// Import our CSS utilities
import "@/styles/mobile-optimizations.css";
import "@/styles/responsive-utils.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";
import { MobileProvider } from "@/contexts/mobile-context";

import localFont from "next/font/local";

// Load local Poppins Black font
const poppinsBlack = localFont({
	src: [
		{
			path: "./_fonts/poppins-black/Poppins-Black.ttf",
			weight: "900",
			style: "normal",
		},
		{
			path: "./_fonts/poppins-black/Poppins-Bold.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "./_fonts/poppins-black/Poppins-ExtraBold.ttf",
			weight: "800",
			style: "normal",
		},
		{
			path: "./_fonts/poppins-black/Poppins-Light.ttf",
			weight: "300",
			style: "normal",
		},
		{
			path: "./_fonts/poppins-black/Poppins-Medium.ttf",
			weight: "500",
			style: "normal",
		},
		{
			path: "./_fonts/poppins-black/Poppins-Regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "./_fonts/poppins-black/Poppins-SemiBold.ttf",
			weight: "600",
			style: "normal",
		},
	],
	variable: "--font-poppins-black",
	display: "swap",
});

const poppins = Poppins({
	variable: "--font-poppins",
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700", "900"],
});

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"],
	weight: ["300", "400", "500", "700", "900"],
});

// Local font for Proxima Nova
const proximaNova = localFont({
	src: [
		{
			path: "./_fonts/proxima-reg.woff2",
			weight: "400",
			style: "normal",
		},
	],
	variable: "--font-proxima-nova",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${roboto.variable} ${poppins.variable} ${poppinsBlack.variable} ${proximaNova.variable} antialiased`}
			>
				<MobileProvider>
					<Navbar />
					{children}
					<Footer />
				</MobileProvider>
			</body>
		</html>
	);
}
